version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lightningbot_app
    restart: always
    # env_file:
    #   - ./.env
    environment:
      APP_HOME: /var/app
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./static:/var/app/static
      - ./staticfiles:/var/app/staticfiles
      - lightning_media:/var/app/media
    networks:
      db_network:
        aliases: [lightningbot_app]
      default:

  nginx: 
    image: nginx:1.21-alpine
    container_name: lightningbot_nginx
    links:
      - web:web
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/app/static
      - ./staticfiles:/var/app/staticfiles
      - ./logs/nginx:/var/log/nginx
      - lightning_media:/var/app/media
    ports:
      - 8038:80
    depends_on:
      - web
    networks:
      nginx-proxy:
        aliases: [lightningbot_nginx]
      default:

volumes:
  lightning_media:

networks:
  db_network:
    external: true
  nginx-proxy:
    external: true

